### ISSUE TITLE
Doesn't work on Buster

### ISSUE THREAD

**Issue by steeley** [twteamware/raspberrypi-ptp#9]
followed instructions  - all went ok with no compile install errors.

but no time stamping!! How can this be fixed?

 ethtool -T eth0
Time stamping parameters for eth0:
Capabilities:
	software-receive      (SOF_TIMESTAMPING_RX_SOFTWARE)
	software-system-clock (SOF_TIMESTAMPING_SOFTWARE)
PTP Hardware Clock: none
Hardware Transmit Timestamp Modes: none
Hardware Receive Filter Modes: none
--------
 systemctl status ptp4l
● ptp4l.service - Precision Time Protocol (PTP) service
   Loaded: loaded (/lib/systemd/system/ptp4l.service; disabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Wed 2020-01-15 10:53:05 GMT; 2s ago
     Docs: man:ptp4l
  Process: 486 ExecStart=/usr/sbin/ptp4l -f /etc/linuxptp/ptp4l.conf -i eth0 (code=exited, status=255/EXCEPTION
 Main PID: 486 (code=exited, status=255/EXCEPTION)

Jan 15 10:53:05 pirtp systemd[1]: Started Precision Time Protocol (PTP) service.
Jan 15 10:53:05 pirtp ptp4l[486]: [67.034] interface 'eth0' does not support requested timestamping mode
Jan 15 10:53:05 pirtp ptp4l[486]: failed to create a clock
Jan 15 10:53:05 pirtp systemd[1]: ptp4l.service: Main process exited, code=exited, status=255/EXCEPTION
Jan 15 10:53:05 pirtp systemd[1]: ptp4l.service: Failed with result 'exit-code'.

**Comment by GillesC** [comment]
I followed the instruction from [here](https://github.com/twteamware/raspberrypi-ptp/issues/6#issuecomment-543744119) and it worked perfectly.

These are the commands (including saving an image to USB):
```bash
# kernel building MIDAS
sudo apt update && sudo apt upgrade
sudo apt install ethtool linuxptp git bc bison flex libssl-dev make exfat-fuse exfat-utils
sudo sed -i -e 's/time_stamping.*$/time_stamping\t\tsoftware/' /etc/linuxptp/ptp4l.conf
git clone --depth=1 --branch rpi-5.6.y https://github.com/raspberrypi/linux
cd linux
KERNEL=kernel7l
make bcm2711_defconfig
# change in .config: CONFIG_LOCALVERSION="-v7l-MIDAS_KERNEL"
make -j6 zImage modules dtbs
echo 'CONFIG_NETWORK_PHY_TIMESTAMPING=y' >> .config
echo 'CONFIG_PTP_1588_CLOCK=y' >> .config
make olddefconfig
make -j6 zImage modules dtbs
sudo make modules_install
sudo cp arch/arm/boot/dts/*.dtb /boot/
sudo cp arch/arm/boot/dts/overlays/*.dtb* /boot/overlays/
sudo cp arch/arm/boot/dts/overlays/README /boot/overlays/
sudo cp arch/arm/boot/zImage /boot/$KERNEL.img
halt

# check if correct
ethtool -T eth0

# CREATE IMAGE
#To check the partitions are what you are expecting:
lsblk
#Create the directory for mounting:
sudo mkdir /media/usb
sudo chmod 775 /media/usb

# Mount the USB connected device.  A single partition Fat32 USB stick on sdb1 in this case:
sudo mount -t exfat /dev/sda1 /media/usb -o rw,umask=0000

# Make an img file from the card inserted in the Pi microSD card slot. Will take some time:
sudo dd if=/dev/mmcblk0 of=/media/usb/imgfile.img bs=1M status=progress
```

**Comment by GillesC** [comment]
I made a fork specifically for the RPI4: https://github.com/versatile-by-dramco/raspberrypi-ptp
